### ISSUE TITLE
Authentication issue (March 2020)

### ISSUE THREAD

**Issue by mrSidX** [adasq/google-alerts-api#29] opened 2020-03-27 03:39 UTC
I am facing that authentication issue as was reported in #14,

I went through all the steps, double triple check.  I had the api working just fine a day or so ago.

I got the DENY and "Moved Temporaritly". from the debug as instructed at the very bottom of the README

I tried to redo the cookies procedure as the same was I did before when I had success.  Only difference this time is when I login to Google and filter the responses,  I click the Response tab and it says "Failed to load response data" 

If I click the Cookies tab, I see bunch of SID keys and nothing works when I generate a cookie with these.  There was something you mentioned about entering a CAPTCHA via command line?  

Can anyone confirm proper functionality on their end?  Am I overlooking something?  Rate limited?  Cursed?  

Thank you for any information in advance regarding my dilemma.

**Comment by mrSidX** [comment] 2020-03-27 21:51
OK I got my side of the issue ironed out... 

For reference,  when you follow the Create Cookie procedure in the README,  please note that you need to log into the account, and then create an alert,  in the Dev Tools Network tab, you'll see a line popup containing "create?x="  and click that and it should have your useable SID keys.   You don't simply log into Google Account to get these, as the SID extracted didn't work for me until I created an Alert.

Thank you for your contributions of this module.

**Comment by adasq** [comment] 2020-03-28 07:04
@mrSidX thank you for the notice. I will check it and update README later on.

**Comment by adasq** [comment] 2020-03-28 14:20
Unfortunately, I was not able to reproduce this problem on my side. 
I linked this issue on README.md if anyone had the same issue. 
Thanks, closing.

**Closed by adasq** 2020-03-28 14:20 UTC
Labels: auth-issues

**Comment by mrSidX** [comment] 2020-03-29 00:49
Thanks for the follow up, as I was able to correct the issue and understand better how to get the proper SIDs.  All is working fine.  Not sure if the keys expire after a period of inactivity, but I made a script to create a repeating RSS 'keep-alive-feed'  every minute or so, and a notification that gets sent to me when the feed contains no 'https'

Thanks again!
